/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiPythonServiceDemoRouteImport } from './routes/api/python-service-demo'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as NPublicIdRouteImport } from './routes/n.$publicId'
import { Route as NotesNewRouteImport } from './routes/notes.new'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiInternalAuthCleanupRouteImport } from './routes/api/internal/auth-cleanup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPythonServiceDemoRoute = ApiPythonServiceDemoRouteImport.update({
  id: '/api/python-service-demo',
  path: '/api/python-service-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const NPublicIdRoute = NPublicIdRouteImport.update({
  id: '/n/$publicId',
  path: '/n/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNewRoute = NotesNewRouteImport.update({
  id: '/notes/new',
  path: '/notes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAuthCleanupRoute = ApiInternalAuthCleanupRouteImport.update({
  id: '/api/internal/auth-cleanup',
  path: '/api/internal/auth-cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/python-service-demo': typeof ApiPythonServiceDemoRoute
  '/n/$publicId': typeof NPublicIdRoute
  '/notes/new': typeof NotesNewRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/auth-cleanup': typeof ApiInternalAuthCleanupRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/python-service-demo': typeof ApiPythonServiceDemoRoute
  '/n/$publicId': typeof NPublicIdRoute
  '/notes/new': typeof NotesNewRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/auth-cleanup': typeof ApiInternalAuthCleanupRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/python-service-demo': typeof ApiPythonServiceDemoRoute
  '/n/$publicId': typeof NPublicIdRoute
  '/notes/new': typeof NotesNewRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/auth-cleanup': typeof ApiInternalAuthCleanupRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/python-service-demo'
    | '/n/$publicId'
    | '/notes/new'
    | '/docs/'
    | '/api/auth/$'
    | '/api/internal/auth-cleanup'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/python-service-demo'
    | '/n/$publicId'
    | '/notes/new'
    | '/docs'
    | '/api/auth/$'
    | '/api/internal/auth-cleanup'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/python-service-demo'
    | '/n/$publicId'
    | '/notes/new'
    | '/docs/'
    | '/api/auth/$'
    | '/api/internal/auth-cleanup'
    | '/_authenticated/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPythonServiceDemoRoute: typeof ApiPythonServiceDemoRoute
  NPublicIdRoute: typeof NPublicIdRoute
  NotesNewRoute: typeof NotesNewRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalAuthCleanupRoute: typeof ApiInternalAuthCleanupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/python-service-demo': {
      id: '/api/python-service-demo'
      path: '/api/python-service-demo'
      fullPath: '/api/python-service-demo'
      preLoaderRoute: typeof ApiPythonServiceDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$publicId': {
      id: '/n/$publicId'
      path: '/n/$publicId'
      fullPath: '/n/$publicId'
      preLoaderRoute: typeof NPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/new': {
      id: '/notes/new'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof NotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/auth-cleanup': {
      id: '/api/internal/auth-cleanup'
      path: '/api/internal/auth-cleanup'
      fullPath: '/api/internal/auth-cleanup'
      preLoaderRoute: typeof ApiInternalAuthCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPythonServiceDemoRoute: ApiPythonServiceDemoRoute,
  NPublicIdRoute: NPublicIdRoute,
  NotesNewRoute: NotesNewRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalAuthCleanupRoute: ApiInternalAuthCleanupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
